---
abstract: 'A container for arbitrary data that JSONifies on demand.'
author:
  - 'Kent Fredric <kentfredric@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0.89'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: '0'
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-File-FromCode-JSON
provides:
  Dist::Zilla::File::FromCode::JSON:
    file: lib/Dist/Zilla/File/FromCode/JSON.pm
    version: '0.001000'
requires:
  Dist::Zilla::File::FromCode: '0'
  Module::Runtime: '0'
  Moose: '0'
  perl: '5.008'
  strict: '0'
  utf8: '0'
  warnings: '0'
version: '0.001000'
x_BuiltWith:
  modules:
    CPAN::Meta: '2.142060'
    Dist::Zilla::App::Command::bakeini: '0.001001'
    Dist::Zilla::File::FromCode: '5.020'
    Dist::Zilla::Plugin::Authority: '1.006'
    Dist::Zilla::Plugin::AutoPrereqs: '5.020'
    Dist::Zilla::Plugin::BumpVersionAfterRelease: '0.002'
    Dist::Zilla::Plugin::ConfirmRelease: '5.020'
    Dist::Zilla::Plugin::CopyFilesFromBuild: '0.103510'
    Dist::Zilla::Plugin::EOLTests: '0.02'
    Dist::Zilla::Plugin::Git::Check: '2.023'
    Dist::Zilla::Plugin::Git::Commit: '2.023'
    Dist::Zilla::Plugin::Git::CommitBuild: '2.023'
    Dist::Zilla::Plugin::Git::GatherDir: '2.023'
    Dist::Zilla::Plugin::Git::NextRelease: '0.002011'
    Dist::Zilla::Plugin::Git::Tag: '2.023'
    Dist::Zilla::Plugin::GithubMeta: '0.46'
    Dist::Zilla::Plugin::License: '5.020'
    Dist::Zilla::Plugin::MakeMaker: '5.020'
    Dist::Zilla::Plugin::Manifest: '5.020'
    Dist::Zilla::Plugin::ManifestSkip: '5.020'
    Dist::Zilla::Plugin::MetaConfig: '5.020'
    Dist::Zilla::Plugin::MetaData::BuiltWith: '1.001000'
    Dist::Zilla::Plugin::MetaJSON: '5.020'
    Dist::Zilla::Plugin::MetaProvides::Package: '2.000003'
    Dist::Zilla::Plugin::MetaTests: '5.020'
    Dist::Zilla::Plugin::MetaYAML: '5.020'
    Dist::Zilla::Plugin::MinimumPerl: '1.003'
    Dist::Zilla::Plugin::PodCoverageTests: '5.020'
    Dist::Zilla::Plugin::PodSyntaxTests: '5.020'
    Dist::Zilla::Plugin::PodWeaver: '4.005'
    Dist::Zilla::Plugin::Prereqs: '5.020'
    Dist::Zilla::Plugin::Prereqs::Recommend::MatchInstalled: '0.002000'
    Dist::Zilla::Plugin::ReadmeAnyFromPod: '0.141760'
    Dist::Zilla::Plugin::ReadmeFromPod: '0.21'
    Dist::Zilla::Plugin::RewriteVersion::Sanitized: '0.001001'
    Dist::Zilla::Plugin::RunExtraTests: '0.022'
    Dist::Zilla::Plugin::Test::CPAN::Changes: '0.008'
    Dist::Zilla::Plugin::Test::Compile::PerFile: '0.002001'
    Dist::Zilla::Plugin::Test::Kwalitee: '2.07'
    Dist::Zilla::Plugin::Test::MinimumVersion: '2.000005'
    Dist::Zilla::Plugin::Test::Perl::Critic: '2.112410'
    Dist::Zilla::Plugin::Test::ReportPrereqs: '0.018'
    Dist::Zilla::Plugin::TestRelease: '5.020'
    Dist::Zilla::Plugin::Twitter: '0.025'
    Dist::Zilla::Plugin::UploadToCPAN: '5.020'
    Dist::Zilla::PluginBundle::Author::KENTNL: '2.016007'
    ExtUtils::MakeMaker: '6.98'
    File::Spec: '3.48'
    Module::Runtime: '0.014'
    Moose: '2.1210'
    Pod::Coverage::TrustPod: '0.100003'
    Test::CPAN::Changes: '0.30'
    Test::CPAN::Meta: '0.23'
    Test::Kwalitee: '1.19'
    Test::More: '1.001003'
    Test::Pod: '1.48'
    Test::Pod::Coverage: '1.10'
    strict: '1.08'
    utf8: '1.14'
    warnings: '1.24'
  perl:
    original: v5.21.1
    qv: 1
    version:
      - 5
      - 21
      - 1
  perl-config:
    gccversion: 4.8.3
    myarchname: x86_64-linux
    osname: linux
  platform: linux
  uname: 'Linux 3.15.5-aufs x86_64 GenuineIntel GNU/Linux'
x_Dist_Zilla:
  perl:
    version: '5.021001'
  plugins:
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::KENTNL/MetaConfig'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::KENTNL/GithubMeta'
      version: '0.46'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@Author::KENTNL/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: '5.020'
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
      name: '@Author::KENTNL/MetaProvides::Package'
      version: '2.000003'
    -
      class: Dist::Zilla::Plugin::MetaData::BuiltWith
      config:
        Dist::Zilla::Plugin::MetaData::BuiltWith:
          _stash_key: x_BuiltWith
          show_config: '1'
          show_uname: '1'
          uname:
            uname_args:
              - -s
              - -o
              - -r
              - -m
              - -i
            uname_call: uname
      name: '@Author::KENTNL/MetaData::BuiltWith'
      version: '1.001000'
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      config:
        Dist::Zilla::Plugin::Git::GatherDir:
          include_untracked: '0'
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::KENTNL/Git::GatherDir'
      version: '2.023'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::KENTNL/License'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::KENTNL/MetaJSON'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::KENTNL/MetaYAML'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::KENTNL/Manifest'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: '@Author::KENTNL/CopyXBuild'
      version: '0.103510'
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Author::KENTNL/MetaTests'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::KENTNL/PodCoverageTests'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::KENTNL/PodSyntaxTests'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: '@Author::KENTNL/Test::ReportPrereqs'
      version: '0.018'
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee
      name: '@Author::KENTNL/Test::Kwalitee'
      version: '2.07'
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@Author::KENTNL/EOLTests'
      version: '0.02'
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Author::KENTNL/Test::MinimumVersion'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::KENTNL/Test::Compile::PerFile/AUTOVIV/:InstallModulesPM'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::Test::Compile::PerFile
      config:
        Dist::Zilla::Plugin::Test::Compile::PerFile:
          file:
            - lib/Dist/Zilla/File/FromCode/JSON.pm
          path_translator: base64_filter
          prefix: t/00-compile
          skip: []
          test_template: 01-basic.t.tpl
          xt_mode: ~
      name: '@Author::KENTNL/Test::Compile::PerFile'
      version: '0.002001'
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: '@Author::KENTNL/Test::Perl::Critic'
      version: '2.112410'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::KENTNL/ManifestSkip'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::RewriteVersion::Sanitized
      config:
        Dist::Zilla::Role::Version::Sanitize:
          mantissa: '6'
          normal_form: numify
      name: '@Author::KENTNL/RewriteVersion::Sanitized'
      version: '0.001001'
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::SingleEncoding
              name: -SingleEncoding
              version: '4.006'
            -
              class: Pod::Weaver::Section::Name
              name: Name
              version: '4.006'
            -
              class: Pod::Weaver::Section::Version
              name: Version
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: prelude
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: PRIVATE_ATTRIBUTES
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: PRIVATE_METHODS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Leftovers
              name: Leftovers
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: postlude
              version: '4.006'
            -
              class: Pod::Weaver::Section::Authors
              name: Authors
              version: '4.006'
            -
              class: Pod::Weaver::Section::Legal
              name: Legal
              version: '4.006'
      name: '@Author::KENTNL/PodWeaver'
      version: '4.005'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::KENTNL/AutoPrereqs'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: suggests
      name: '@Author::KENTNL/BundleDevelSuggests'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Author::KENTNL/MinimumPerl'
      version: '1.003'
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::KENTNL/Authority'
      version: '1.006'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: '10'
      name: '@Author::KENTNL/MakeMaker'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: '@Author::KENTNL/ReadmeFromPod'
      version: '0.21'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::KENTNL/ReadmeAnyFromPod'
      version: '0.141760'
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@Author::KENTNL/Test::CPAN::Changes'
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: '10'
      name: '@Author::KENTNL/RunExtraTests'
      version: '0.022'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::KENTNL/TestRelease'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::KENTNL/ConfirmRelease'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::KENTNL/Git::Check'
      version: '2.023'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
          time_zone: local
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::KENTNL/commit_dirty_files'
      version: '2.023'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          signed: '0'
          tag: 0.001000-source
          tag_format: '%v-source'
          tag_message: v%v
          time_zone: local
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::KENTNL/tag_master'
      version: '2.023'
    -
      class: Dist::Zilla::Plugin::Git::NextRelease
      name: '@Author::KENTNL/Git::NextRelease'
      version: '0.002011'
    -
      class: Dist::Zilla::Plugin::BumpVersionAfterRelease
      name: '@Author::KENTNL/BumpVersionAfterRelease'
      version: '0.002'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
          time_zone: local
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match:
            - (?^u:^lib/)
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::KENTNL/commit_release_changes'
      version: '2.023'
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      config:
        Dist::Zilla::Plugin::Git::CommitBuild:
          branch: build/%b
          build_root: ~
          message: 'Build results of %h (on %b)'
          multiple_inheritance: '0'
          release_branch: releases
          release_message: 'Build results of %h (on %b)'
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::KENTNL/Git::CommitBuild'
      version: '2.023'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: releases
          signed: '0'
          tag: '0.001000'
          tag_format: '%v'
          tag_message: v%v
          time_zone: local
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::KENTNL/tag_release'
      version: '2.023'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::KENTNL/UploadToCPAN'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::Twitter
      name: '@Author::KENTNL/Twitter'
      version: '0.025'
    -
      class: Dist::Zilla::Plugin::Prereqs::Recommend::MatchInstalled
      config:
        Dist::Zilla::Plugin::Prereqs::Recommend::MatchInstalled:
          applyto_map:
            - 'build.requires = build.recommends'
            - 'test.requires = test.recommends'
            - 'runtime.requires = runtime.recommends'
            - 'configure.requires = configure.recommends'
            - 'develop.requires = develop.recommends'
          applyto_phase:
            - build
            - test
            - runtime
            - configure
            - develop
          modules:
            - ExtUtils::MakeMaker
            - Test::More
      name: '@Author::KENTNL/Prereqs::Recommend::MatchInstalled'
      version: '0.002000'
    -
      class: Dist::Zilla::Plugin::Prereqs::Recommend::MatchInstalled
      config:
        Dist::Zilla::Plugin::Prereqs::Recommend::MatchInstalled:
          applyto_map:
            - 'develop.suggests = develop.suggests'
          applyto_phase:
            - develop
          modules:
            - Dist::Zilla::PluginBundle::Author::KENTNL
            - Dist::Zilla::App::Command::bakeini
      name: '@Author::KENTNL/always_latest_develop_bundle'
      version: '0.002000'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: '@Author::KENTNL/::Role::BundleDeps'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::KENTNL/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: '5.020'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.020'
x_authority: cpan:KENTNL
